name: Deploy Flutter Web Apps to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Flutter SDKのセットアップ
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.5"
          channel: "stable"
          cache: true

      # 依存関係の取得（メインプロジェクト）
      - name: Install dependencies
        run: flutter pub get

      # 依存関係の取得（Widgetbook）
      - name: Install Widgetbook dependencies
        run: |
          cd lib/widgetbook
          flutter pub get

      # Widgetbookアプリのビルド（/screens用）
      - name: Build Widgetbook app
        run: |
          cd lib/widgetbook
          flutter build web --web-renderer canvaskit --base-href /pd_share_sample/screens/

      # Widgetbookのビルド成果物を一時ディレクトリに移動
      - name: Copy Widgetbook build to temp
        run: |
          mkdir -p deploy/screens
          cp -r lib/widgetbook/build/web/* deploy/screens/

      # フロー確認用アプリのビルド（/flow用）
      - name: Build main app
        run: flutter build web -t lib/main.dart --web-renderer canvaskit --base-href /pd_share_sample/flow/

      # メインアプリのビルド成果物を一時ディレクトリに移動
      - name: Copy main app build to temp
        run: |
          mkdir -p deploy/flow
          cp -r build/web/* deploy/flow/

      # GitHub Pagesへデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
